version: '3'

services:
  db-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "******************"
    ports:
      - "15432:5432"
    volumes:
    - /home/juan/Dev/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "juanccdesouza@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "******************"
    ports:
      - "16543:80"
    depends_on:
      - db-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
